
import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo } from "next/font/google";
import "./global.css";
import { Navbar } from "@/_Components/Navbar";
import Footer from "@/_Components/Footer";
import { Toaster } from "@/components/ui/sonner";

import MySessionProviders from "@/_Providers/MySessionProviders";
import CartContextProvider from "@/_Context/CartContextProvider";
import { getUserCart } from "@/_Card.Actions/Card.actions";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],

});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const userCart= await getUserCart()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo.variable}  font-exo    antialiased `}
      >
      <MySessionProviders>


          <CartContextProvider userCart={userCart}>
        <Navbar/>
        <Toaster/>
        {children}
        <Footer />


          </CartContextProvider>

      

      </MySessionProviders>
        
      </body>
    </html>
  );
}